### ISSUE TITLE
Gradient objectBoundingBox and Transform

### ISSUE THREAD

**Issue by conversy** [mokafolio/Tarp#16]
Hello,

not an issue but features request.

In order to be more easily compilant with SVG, it would be nice to scale the gradient origin and destination according to the bounding box of the object it applies to. I can give it a try if you give me hints on how this could be done in the actual Tarp architecture: another gradient property, and the  application of a scale before rendering an object?

Similarly, gradient transform would be helpful. There are some paint transform attributes, I wonder if these are the intended usage.

Best, Stéphane

**Comment by mokafolio** [comment]
Hi Stéphane,

My gut feeling is that I'd rather not do this inside of Tarp. Especially doing such a strange transformation automatically seems not very intuitive and adding it as an option will bloat the library. If you need the behavior that you are describing (I am not sure if that is what SVG actually does), I'd encourage you to implement that outside of tarp. You can easily apply whatever scale/transform you desire using the paint transform functions. Hope that makes sense!

**Comment by conversy** [comment]
The thing is that I need the object bounding box to apply the transformation. Will it invalidate the gradient cache each time I use it since I will be modifying the paintTransform?

**Comment by conversy** [comment]
Yes, of course, you're perfectly right! I need to keep the style then...

**Comment by conversy** [comment]
btw is there a helper function to get the bounds of a path? I could not find one but I may have overseen it...

**Comment by mokafolio** [comment]
No there intentionally is not. Tarp is really only concerned with rendering not any kind of bezeir/path/bounds calculation so I intentionally don't expose it through the API (the bounds for rendering are basically approximations). Can you please point me to the svg reference of the thing you are trying to do so I can wrap my head around it? 

Why do you need to keep the style? The paint transforms are set per path, not per style.

**Comment by conversy** [comment]
https://www.w3.org/TR/SVGTiny12/coords.html#ObjectBoundingBoxUnits

for the paintTransform: I only had a glance at it, and thought incorrectly that they were attached to style. I understand now that they are set per path.

**Comment by mokafolio** [comment]
Well, so the reference basically tells you which transform you need to create:
`[ (maxx-minx) 0 0 (maxy-miny) minx miny ]`

For that, as you correctly said, you need to know the bounds of the shape though. As I said, I'd rather not have that in Tarp as that will lead down a path that will eventually make Tarp a bezier computing library and not just a rendering library. If you need help computing the bounds of a path, I can point you towards the right direction. You can either flatten the path and simply compute the bounds that way (which is what tarp does during rendering) or actually use bezier related formulas to compute the bounds (which is what I usually do in higher level vector graphics libraries). This is usually a good starting point for all bezier math related questions: https://pomax.github.io/bezierinfo/#boundingbox (linked the bounding box section)

**Comment by conversy** [comment]
thanks for the pointers. I found a way to implement that outside of tarp.

**Comment by mokafolio** [comment]
Great, I'll close this for now, feel free to reopen if you run into any issues!
