### ISSUE TITLE
CPU rendering backend

### ISSUE THREAD

**Issue by dumblob** [mokafolio/Tarp#3]
This might be of an interest for you. A CPU rendering backend based on Blend 2D could be even faster than OpenGL in many cases.

https://blend2d.com/

https://github.com/blend2d

**Comment by lieff** [comment]
@dumblob Hmm, https://github.com/blend2d/b2d shows "This repository is empty.".

**Comment by mokafolio** [comment]
Generally speaking I'd be down to add a CPU based backend, but the focus really is to have a dependency free solution + the API is focussed on GPU based approaches in a lot of ways at this point int time. Open to someone taking a stab at it though :).

**Comment by dumblob** [comment]
https://github.com/mokafolio/Tarp/issues/3#issuecomment-391076291:
>@dumblob Hmm, https://github.com/blend2d/b2d shows "This repository is empty.".

@kobalicek any progress in publishing the source?

**Comment by mokafolio** [comment]
I'll close this for now!
